//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DU.Themes.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DU.Themes.Views.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmanību.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atcelt piekeikumu.
        /// </summary>
        public static string CancelRequest {
            get {
                return ResourceManager.GetString("CancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveidot.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveidots.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apstiprināt piteikumu un izveidot tēmu.
        /// </summary>
        public static string CreateTheme {
            get {
                return ResourceManager.GetString("CreateTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveidot mācību gādu.
        /// </summary>
        public static string CreateYear {
            get {
                return ResourceManager.GetString("CreateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzest.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediģēt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beiguma macibas gads.
        /// </summary>
        public static string EndYear {
            get {
                return ResourceManager.GetString("EndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vārds.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzvards.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vajag labojumi.
        /// </summary>
        public static string NeedImprovements {
            get {
                return ResourceManager.GetString("NeedImprovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav neviena izveidota gāda.
        /// </summary>
        public static string NoYearCreated {
            get {
                return ResourceManager.GetString("NoYearCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieprasījumi.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saglabāt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakuma macibas gads.
        /// </summary>
        public static string StartYear {
            get {
                return ResourceManager.GetString("StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Id.
        /// </summary>
        public static string StudentIdentifier {
            get {
                return ResourceManager.GetString("StudentIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mācības gāda sakums.
        /// </summary>
        public static string StudyYearBeggining {
            get {
                return ResourceManager.GetString("StudyYearBeggining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mācības gāda beigums.
        /// </summary>
        public static string StudyYearEnding {
            get {
                return ResourceManager.GetString("StudyYearEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasniedzejs.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tēma Angliski.
        /// </summary>
        public static string ThemeEng {
            get {
                return ResourceManager.GetString("ThemeEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tēma Latviski.
        /// </summary>
        public static string ThemeLv {
            get {
                return ResourceManager.GetString("ThemeLv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mācību gādu saraksts.
        /// </summary>
        public static string YearListHeading {
            get {
                return ResourceManager.GetString("YearListHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gāds.
        /// </summary>
        public static string YearName {
            get {
                return ResourceManager.GetString("YearName", resourceCulture);
            }
        }
    }
}
