//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DU.Themes.Validaiton {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DU.Themes.Validaiton.ValidationErrors", typeof(ValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentam jau ir izveidots aktīvs pieteikums/tēma.
        /// </summary>
        internal static string AlreadyHasActive {
            get {
                return ResourceManager.GetString("AlreadyHasActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mācību gada beigu datumam ir jābūt mazākam nekā sākuma datumam.
        /// </summary>
        internal static string EndLesserThanStart {
            get {
                return ResourceManager.GetString("EndLesserThanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beigu gada.
        /// </summary>
        internal static string EndYear {
            get {
                return ResourceManager.GetString("EndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; lauks ir obligāts.
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir jābūt tikai vienai aktīvai tēmai.
        /// </summary>
        internal static string OnlyOneActiveTheme {
            get {
                return ResourceManager.GetString("OnlyOneActiveTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sākuma gada.
        /// </summary>
        internal static string StartYear {
            get {
                return ResourceManager.GetString("StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenta.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasniedzēja.
        /// </summary>
        internal static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tēma Angliski.
        /// </summary>
        internal static string ThemeEng {
            get {
                return ResourceManager.GetString("ThemeEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tēma Latviski.
        /// </summary>
        internal static string ThemeLv {
            get {
                return ResourceManager.GetString("ThemeLv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemā jau ir reģistrēts šāds mācību gads.
        /// </summary>
        internal static string YearAlreadyExists {
            get {
                return ResourceManager.GetString("YearAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevar izdēst,  jo šis gads tiek izmantots.
        /// </summary>
        internal static string YearIsInUse {
            get {
                return ResourceManager.GetString("YearIsInUse", resourceCulture);
            }
        }
    }
}
